# Generated by Django 3.2.7 on 2021-09-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default='2021-09-28 11.36'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateTimeField(default='2021-09-28 11.36'),
        ),
    ]
