# Generated by Django 3.2.7 on 2021-09-28 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210928_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.CharField(blank=True, default='Не начато', editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 13, 35, 55, 637730)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 13, 35, 55, 637769)),
        ),
    ]
